
const tasoOneTopics = [
    'Mikä sinun nimi on?',
    'Kuinka vanha sinä olet?',
    'Mistä maasta olet kotoisin?',
    'Minkä maalainen sinä olet?',
    'Kuinka montaa kieltä sinä puhut?',
    'Missä sinä asut?',
    'Onko sinulla iso vai pieni perhe?',
    'Onko sinulla siskoja tai veljiä?',
    'Kuinka vanhoja sinun sisarukset ovat?',
    'Vietätkö mieluummin aikaa perheen kanssa vai ystävien kanssa?',
    'Onko sinulla omia lapsia?',
    'Mistä sinä pidät?',
    'Mitä sinä harrastat?',
    'Onko sinulla lemmikkiä?',
    'Missä sinä asuit lapsena?',
    'Mikä sinun äidin nimi on?',
    'Mikä sinun isän nimi on?',
    'Asutko sinä yksin vai jonkun kanssa?',
    'Keitä sinun perheeseen kuuluu?',
    'Onko sinulla muita sukulaisia Suomessa?',
    'Mitä asioita sinä teet perheen kanssa?',
    'Milloin sinä tarvitset sinun perhettä eniten?',
    'Onko teillä usein suuria perhetapaamisia?',
    'Millaisessa talossa sinä asuit, kun olit lapsi?',
    'Keitä sinun perheeseen kuului, kun olit lapsi?',
    'Mitä sinä teit lapsena kavereiden kanssa?',
    'Kuka oli sinun paras kaveri lapsena?',
    'Vierailitko usein sinun isovanhempien luona?',
    'Minkä ikäisenä sinä menit kouluun?',
    'Oliko sinun helppo saada kavereita koulussa?',
    'Mistä kaupungista sinä olet kotoisin?',
    'Mikä on sinun kotimaan pääkaupunki?',
    'Millainen lippu sinun kotimaassa on?',
    'Mitä asioita sinun kotimaassa voi harrastaa?',
    'Millaisia eläimiä sinun kotimaassa on?',
    'Keitä julkisuuden henkilöitä on sinun kotimaassa?',
    'Mitä juhlia sinun kotimaassa vietetään?',
    'Mitkä ovat tyypillisiä ammatteja sinun kotimaassa?',
    'Mitä sinun mieleen tulee, kun kuulet sanan Suomi?',
    'Mitä hyviä ja huonoja asioita Suomessa on?',
    'Mistä Suomi on tunnettu?',
    'Mikä on sinun lempikaupunki Suomessa?',
    'Missä kaupungeissa sinä olet käynyt Suomessa?',
    'Millainen on Suomen lippu?',
    'Mitä asioita Suomessa voi harrastaa?',
    'Millaisessa kodissa sinä asut?',
    'Mistä asiasta pidät eniten sinun kodissa?',
    'Onko sinun kodissa jokin asia, josta sinä et pidä?',
    'Pidätkö siitä paikasta, jossa sinun koti sijaitsee?',
    'Millainen koti sinulla oli omassa kotimaassa?',
    'Tykkäätkö olla kotona yksin?',
    'Asutko sinä yksin vai jonkun kanssa?',
    'Mitä sinä teet kotona?',
    'Teetkö sinä kotitöitä?',
    'Kuka laittaa ruokaa sinun kotona?',
    'Asuisitko mieluummin omakotitalossa vai kerrostalossa?',
    'Oletko sinä koti-ihminen vai viihdytkö paremmin kaupungilla?',
    'Käytkö sinä saunassa?',
    'Kutsutko mielelläsi vieraita kotiisi vai käytkö mieluummin itse kaverin kotona?',
    'Missä sijaitsi/sijaitsee sinun koti, jossa olet viihtynyt parhaiten?',
    'Mikä oli sinun lempiaine koulussa?',
    'Mitä kieliä sinä olet opiskellut koulussa?',
    'Oliko sinulla hyviä kavereita koulussa lapsena?',
    'Mitä sinä haluaisit opiskella?',
    'Millainen on hyvä opettaja?',
    'Millainen on hyvä oppilas?',
    'Mikä on sinun toiveammatti?',
    'Mikä oli sinun haaveammatti lapsena?',
    'Mitä työtä olet tehnyt kotimaassa?',
    'Millainen työ on kivaa?',
    'Millainen työ on tylsää?',
    'Millainen työpaikka on hyvä?',
    'Millaista työtä haluaisit tehdä tulevaisuudessa?',
    'Mitä teit lapsena koulupäivän jälkeen?',
    'Oliko sinulla lapsena lempiopettajaa? Kerro hänestä.',
    'Mistä ruoasta sinä pidät?',
    'Mitä sinä syöt aamupalaksi?',
    'Mitä sinä syöt lounaaksi?',
    'Mistä jälkiruoasta sinä pidät?',
    'Minkä maalaisesta ruoasta sinä pidät?',
    'Mistä juomasta sinä pidät?',
    'Mikä on paras syömäsi ateria?',
    'Mitä ruokaa et suostu syömään?',
    'Laitatko mieluummin itse ruokaa vai syötkö ulkona?',
    'Syötkö yleensä ruokaa yksin vai yhdessä jonkun kanssa?',
    'Voitko olla päivän ilman ruokaa?',
    'Oletko paastonnut?',
    'Pidätkö pikaruoasta?',
    'Oletko allerginen jollekin ruoalle?',
    'Millaisia ruokia osaat tehdä?',
    'Mitä sinä teet vapaa-ajalla?',
    'Mitä sinun kotipaikkakunnalla voi harrastaa?',
    'Mitä sinä teit vapaa-ajalla omassa kotimaassa?',
    'Luetko sinä kirjoja ja lehtiä vapaa-ajalla?',
    'Mistä liikuntalajeista sinä pidät?',
    'Osaatko sinä tehdä käsitöitä? Millaisia käsitöitä sinä osaat tehdä?',
    'Käytkö sinä vapaa-ajalla elokuvissa tai teatterissa?',
    'Millaista musiikkia sinä kuuntelet?',
    'Osaatko sinä soittaa jotain soitinta?',
    'Oletko saanut uusia harrastuksia Suomessa? Kerro niistä.',
    'Pidätkö sinä matkustamisesta?',
    'Missä maissa sinä olet käynyt?',
    'Millä kulkuvälineillä sinä tykkäät matkustaa?',
    'Matkustatko mieluiten yksin, kavereiden kanssa vai perheen kanssa?',
    'Katsotko televisiosta matkailuohjelmia?',
    'Pidätkö sinä urheilusta?',
    'Mikä on sinun lempiurheilulaji?',
    'Mitä urheilulajia sinun kotimaassa harrastetaan?',
    'Kumpaa teet mieluummin: urheilet vai katsot urheilua?',
    'Haluaisitko, että urheilu olisi sinun ammatti?',
    'Kuinka usein luet urheilu-uutisia?',
    'Urheilitko lapsena?',
    'Miksi monet ihmiset pitävät urheilusta?',
    'Miksi jotkut ihmiset eivät ole kiinnostuneita urheilusta?',
    'Kuka on sinun lempiurheilutähti?',
    'Pidätkö sinä extreme-urheilulajeista?',
    'Katsotko mieluummin urheilua kotona, stadionilla vai baarissa kavereiden kanssa?',
    'Seuraatko olympialaisia?',
    'Käytkö jalkapallo-otteluissa?',
    'Minkä urheilulajin haluaisit oppia?',
    'Mikä on sinun lempieläin?',
    'Mistä eläimistä sinä pidät?',
    'Luettele viisi suomalaista eläintä.',
    'Luettele viisi eläintä, joita löytyy sinun kotimaasta.',
    'Mistä vuodenajasta sinä pidät?',
    'Vietätkö mielelläsi aikaa luonnossa?',
    'Mitä luonnossa voi harrastaa?',
    'Mikä on sinun lempikasvi?',
    'Mitä kasveja ja marjoja sinä tunnet?',
    'Keräätkö kasveja tai marjoja luonnosta?',
    'Onko sinun kotimaassa ja Suomessa joitain samoja kasveja tai marjoja?',
    'Pidätkö retkeilystä?',
    'Pidätkö veneilystä?',
    'Pidätkö kalastamisesta?',
    'Osaatko suunnistaa vai eksytkö helposti?',
    'Milloin käytit tietokonetta ensimmäisen kerran?',
    'Kuinka usein sinä käytät tietokonetta?',
    'Kuinka usein sinä käytät Internetiä?',
    'Mikä on paras puoli tietokoneissa?',
    'Mikä on huonoin puoli tietokoneissa?',
    'Pidätkö sinä tietokoneista?',
    'Tiedätkö paljon tietokoneista?',
    'Mihin sinä käytät Internettiä?',
    'Onko sinulla paljon nettiystäviä?',
    'Mitä verkkosivuja sinä yleensä käytät?',
    'Käytätkö mieluiten pöytäkonetta, kannettavaa tietokonetta vai älypuhelinta?',
    'Pelaatko tietokonepelejä? Mitä pelejä pelaat?',
    'Kumpi on sinun mielestä parempi: Mac vai PC?',
    'Opiskeletko sinä Internetin avulla?',
    'Onko sinusta tietokoneen ja Internetin käyttö vaikeaa?',
    'Mitä ohjelmia sinä katsot televisiosta?',
    'Käytkö sinä elokuvissa?',
    'Katsotko sinä elokuvia kotona?',
    'Minkä elokuvan sinä katsoit viimeksi?',
    'Kuka on sinun lempinäyttelijä?',
    'Mikä on paras elokuva, jonka sinä olet katsonut?',
    'Mikä on huonoin elokuva, jonka sinä olet katsonut?',
    'Mitä musiikkia kuuntelet?',
    'Mikä on sinun lempibändi/-laulaja?',
    'Mistä kuuntelet musiikkia?',
    'Soitatko jotain soitinta?',
    'Mikä on paras paikka ja aika kuunnella musiikkia?',
    'Sano yksi suosittu suomalainen bändi.',
    'Sano yksi suosittu bändi tai laulaja sinun kotimaasta.',
    'Mikä on sinun mielestä maailman kaunein ääni.',
    'Kenen kanssa sinä vietät aikaa?',
    'Ketkä ovat sinun ystäviä?',
    'Minkä maalaisia ystäviä sinulla on?',
    'Mitä sinä teet ystävien kanssa?',
    'Oletko sinä naimisissa?',
    'Onko sinulla tyttökaveria/poikakaveria?',
    'Mitä sinä muistat sinun ensimmäisistä treffeistä?',
    'Kumpi maksaa ensimmäisillä treffeillä?',
    'Voisitko sinä mennä sokkotreffeille?',
    'Käyttäisitkö koskaan Internetin nettisivustoa?',
    'Luuletko, että Internetin kautta voi löytää hyviä ystäviä?',
    'Millainen on hyvä ystävä?',
    'Mikä uskonto on yleinen sinun kotimaassa?',
    'Mikä on sinulle tärkeä uskonnollinen juhlapyhä?',
    'Onko Suomessa ja sinun kotimaassa erilaisia juhlapyhiä?'
]
const tasoTwoTopics = [
    'Millainen koti sinulla on?',
    'Millainen perhe sinulla on?',
    'Mitä tekisit, jos voittaisit lotossa?',
    'Oletko sinä perheihminen?',
    'Mikä oli sinun toiveammatti, kun olit lapsi?',
    'Keitä ihmisiä kuuluu sinun lähiperheeseen?',
    'Keitä ihmisiä kuuluu sinun sukuun?',
    'Mikä on parasta sinun perheessä?',
    'Muistatko sinun ensimmäisen opettajan? Millainen hän oli?',
    'Mistä juhlista/lomista pidit eniten lapsena?',
    'Kuvaile, miltä sinun kotimaassa näyttää.',
    'Millainen ilmasto sinun kotimaassa on?',
    'Palaisitko omaan kotimaahaan, jos se olisi mahdollista? Miksi?',
    'Kuvaile suomalaisia vuodenaikoja.',
    'Millainen on tyypillinen suomalainen sinun mielestä?',
    'Oletko tyytyväinen sinun kodin sisustukseen ja huonekaluihin?',
    'Mitä sinä haluaisit muuttaa tai remontoida sinun kodissa?',
    'Onko sinulla puutarha? Pidätkö puutarhanhoidosta?',
    'Oletko samaa mieltä sanonnasta "koti on siellä, missä sydän on"?',
    'Millaisia taloja ja koteja sinun kotimaassa on?',
    'Mitä mieltä sinä olet koulupuvusta?',
    'Pitäisikö koulussa olla kouluruoka vai pitäisikö oppilaiden tuoda omat eväät?',
    'Millaisia rangaistuksia opettaja käytti koulussa sinun kotimaassa?',
    'Mitä mieltä olet erilaisista rangaistuksista koulussa?',
    'Miten sinä opit parhaiten?',
    'Katsotko televisiosta ruokaohjelmia?',
    'Millaista ruokaa Suomessa syödään?',
    'Millaista ruokaa sinun kotimaassa syödään?',
    'Pidätkö enemmän suomalaisesta vai sinun kotimaan ruoasta? Miksi?',
    'Mitä ruokaa haluaisit maistaa, mitä et ole koskaan maistanut?',
    'Millainen on hyvä harrastus?',
    'Minkä uuden taidon sinä haluaisit oppia?',
    'Mitä sinun kotipaikkakunnalla voi harrastaa ilmaiseksi?',
    'Mikä on parasta matkustamisessa?',
    'Minne sinä haluaisit matkustaa? Miksi?',
    'Uskotko, että on hienoa olla urheilutähti?',
    'Oletko sitä mieltä, että jalkapallo on maailman suosituin urheilulaji? Miksi?',
    'Saavatko urheilutähdet sinusta sopivaa palkkaa?',
    'Haluaisitko kokeilla jotain extreme-urheilulajia, kuten laskuvarjohyppyä tai varjoliitoa?',
    'Seuraatko jonkin urheilujoukkueen pelejä?',
    'Kasvatatko itse yrttejä tai vihanneksia kotona?',
    'Onko sinun kotimaassa usein luonnonkatastrofeja?',
    'Onko sinun mielestä lemmikki perheenjäsen vai ei? Perustele.',
    'Millainen luonto on sinun kotimaassa?',
    'Onko luonto sinulle tärkeä?',
    'Mitä asiaa jäät kaipaamaan, jos sinulta otetaan pois tietokone?',
    'Mitä tietokoneohjelmia sinä käytät?',
    'Mitä tietokoneohjelmia haluaisit oppia käyttämään?',
    'Mitä sosiaalisen median sovelluksia sinä käytät (esim. Facebook, Twitter, Youtube)?',
    'Millaista haittaa tietokoneen käyttö voi aiheuttaa?',
    'Millaisista elokuvista sinä pidät? (toiminta, komedia, draama, kauhu)',
    'Millainen on hyvä elokuva?',
    'Luetko mieluummin kirjan vai katsotko elokuvan, joka perustuu kirjaan?',
    'Voiko musiikkimausta olla eri mieltä?',
    'Miksi ihmiset pitävät musiikista niin paljon?',
    'Mikä on kaverin ja ystävän ero?',
    'Onko parempi mennä naimisiin jonkun kanssa, jolla on sama etninen tausta, uskonto ja/tai sosiaalinen asema?',
    'Miten sinä autat toisia ihmisiä arkipäivänä?',
    'Millaisia hyviä tekoja jokainen voi tehdä?',
    'Mikä on sinun mielestä väärää ja oikeaa?'
]
const tasoThreeTopics = [
    'Mitä tekisit toisin, jos voisit mennä ajassa taaksepäin?',
    'Kerro yksi tulevaisuuden unelma.',
    'Muistatko sinun ensimmäisen koulupäivän? Kerro siitä.',
    'Oliko sinulla toiveammatteja lapsuudessa? Kerro niistä.',
    'Missä haluaisit asua, jos voisit valita minkä tahansa paikan?',
    'Pidätkö enemmän ydinperheen vai laajan perheyhteisön ajatuksesta?',
    'Mitä perhe sinulle merkitsee?',
    'Mikä on sinun mielipide "täydellisestä perheestä"?',
    'Oliko sinulla lempisatua tai lempitarinaa? Kerro siitä.',
    'Muistatko jonkun hetken tai tilanteen sinun lapsuudesta, joka oli tärkeä sinulle?',
    'Mitä asioita muuttaisit sinun kotimaassa, jos voisit?',
    'Mitä hyviä asioita toisit sinun kotimaasta Suomeen, jos se olisi mahdollista?',
    'Mitä hyviä asioita veisit Suomesta sinun kotimaahan?',
    'Miten Suomi eroaa sinun kotimaasta?',
    'Millaisena näet sinun tulevaisuuden Suomessa?',
    'Mikä tekee kodista kotoisan?',
    'Millainen on sinun unelmien koti? Kuvaile sitä.',
    'Mikä on mielestäsi kodin ja asunnon ero?',
    'Millaisessa kodissa et haluaisi asua?',
    'Mitä sinun mielestä tarkoittaa sanonta "keittiö on kodin sydän"?',
    'Kerro sinun parhaasta koulumuistosta.',
    'Millainen työkulttuuri Suomessa on?',
    'Millainen työkulttuuri sinun kotimaassa on?',
    'Miten suomalainen koulu eroaa sinun kotimaan koulusta?',
    'Mitä mieltä olet koulukiusaamisesta?',
    'Oletko samaa mieltä sanonnan kanssa "olet mitä syöt"?',
    'Millaisen aterian sinä valmistaisit sinun ystäville?',
    'Millaista ruokaa tarjoiltaisiin ravintolassa, jos sinä omistaisit sen?',
    'Millainen olisi sinun unelma-ateria?',
    'Kuinka nälkäinen olet tämän keskustelun jälkeen?',
    'Jos sinulla olisi paljon rahaa, millaisen matkan sinä tekisi!?',
    'Tuntuuko sinusta, että tarvitset lomaa matkustamisen jälkeen?',
    'Miksi ihmisiä kiinnostaa matkustaminen niin paljon?',
    'Mitä sinä harrastaisit, jos voisit Valita minkä tahansa harrastuksen?',
    'Onko sinun mielestä tärkeää, että ihmisellä on harrastuksia?',
    'Miksi urheilu on tärkeää ihmisille?',
    'Uskotko, että urheilu näyttää ihmisen luonteen? Miksi?',
    'Uskotko, että urheilun avulla ihmisiä voidaan pitää erossa päihteistä?',
    'Oliko sinun koulussa lapsena koululiikuntaa? Mitä pidit siitä?',
    'Urheilevatko nuoret mielestäsi tarpeeksi?',
    'Jos sinä olisit eläin, mikä eläin sinä olisit?',
    'Miten Suomen luonto eroaa sinun kotimaan luonnosta?',
    'Onko luonnonsuojelu tärkeää sinun mielestä?',
    'Miten hyödynnät luontoa (ruoka, vapaa-aika)?',
    'Liikuitko lapsena luonnossa? Mitä teit siellä?',
    'Hallitsevatko ihmiset tietokoneita vai tietokoneet ihmisiä?',
    'Mitä asioita toivoisit tietokoneen tekevän, joita tietokone ei pysty nyt tekemään?',
    'Uskotko, että kaukosuhde voi toimia Internetin kautta?',
    'Mitä hyviä ja huonoja puolia on verkkokaupoissa?',
    'Millaista elämä olisi ilman tietokoneita?',
    'Oletko sitä mieltä, että elokuvat ovat tehneet yhteiskunnasta väkivaltaisemman?',
    'Monet ihmiset sanovat, että elokuvat, jotka perustuvat tiettyyn kirjaan, eivät ole niin hyviä kuin itse kirjat. Oletko samaa mieltä? Miksi?',
    'Mikä on parasta piirretyissä elokuvissa?',
    'Mitä musiikki merkitsee sinulle?',
    'Mikä soitin sinä olisit, jos sinun pitäisi valita yksi soitin? Miksi?',
    'Uskotko elämänpituiseen rakkauteen?',
    'Mitä hyviä ja huonoja puolia on järjestetyissä avioliitoissa?',
    'Mitkä asiat ovat sinun mielestä hyviä tavoitteita ja unelmia elämässä?',
    'Mitä asioita sinä muuttaisit maailmassa, jos sinulla olisi valtaa?'
]

const topics = [tasoOneTopics, tasoTwoTopics, tasoThreeTopics];
